### PR TITLE
chore: update msrv version

### LINKED ISSUE #8: Update workflow to latest rust version

### LINKED ISSUE #21: Add Minimum Supported Version
Each cargo crate must specify a minimum supported version so that developers can abide by it

### PR DESCRIPTION
**Pull request by king-11**
Fixes #21
Fixes #8 

Signed-off-by: Lakshya Singh <lakshay.singh1108@gmail.com>

### CODE REVIEW

**Comment by king-11** [comment]
@Cliftonz requesting your review

**Comment by Cliftonz** [comment]
@king-11  Why was this only updated to 1.63? currently 1.72 is the lastest version.

**Comment by king-11** [comment]
The `stable` channel in CI already points to `1.72.1` here I have added in the minimum supported version of our SDK which is `1.63` as of now.

**Comment by king-11** [comment]
@Cliftonz am I missing on something 😅 else or does it look good for merging?

**Comment by Cliftonz** [comment]
Just got lost in the sea of prs, thanks for the ping

**Review by Cliftonz — APPROVED** [review]

**Comment by king-11** [comment]
Shall we merge it now?

**Pull request merged**
